### ISSUE TITLE
Centos 7 error

### ISSUE THREAD

**Issue by NaiCity** [nejdetckenobi/gimme-that#3]
In trying to install clamav-daemon and clamav-freshclam in Centos 7 but getting "No package clamav-daemon No package clamav-freshclam available. I had installed epel earlier. What could be wrong ?

**Comment by nejdetckenobi** [comment]
There are some differences between installing clamav to CentOS and installing clamav to Ubuntu/Debian based distros. Your package manager is right. There are no `clamav-daemon` or `clamav-freshclam` package on CentOS. Can you follow [these](https://linux-audit.com/install-clamav-on-centos-7-using-freshclam/) instructions to install Clamav, instead of mine? Just installation part. Then configure just like in my notes.

**Comment by nejdetckenobi** [comment]
I'll update my notes if that's your solution.

**Comment by nejdetckenobi** [comment]
Tested on CentOS 7 with the link I just gave. I got no error. So, marking this as fixed.
